### PR TITLE
sys has been deprecated - convert usage to util

### PR DESCRIPTION
**Pull request by jmalonzo**
Hi Rob,

The sys module has been deprecated so I changed it's usage in node-xml to util. I'd appreciate the review and possible merge the changes. 

Thanks.

Jan

### CODE REVIEW

**Comment by bigeasy** [comment]
Please apply. Also, @jmalonzo, the use of `sys` in `node-xml.js` is superfluous. You can delete those lines.

**Comment by bigeasy** [comment]
Thank you for applying the pull request. I'm still not seeing the module at `npmjs.org`, though.

http://search.npmjs.org/#/node-xml

**Comment by robrighter** [comment]
Just published it to npm. The new version is 1.0.1.

**Comment by bigeasy** [comment]
Yup. No more bellyaching on the console. Thank you.

**Pull request merged**
